Repository lavanet/lava, pull requests merged in 2023-04, with the labels that each got.

#424 adding upgrade handler for 0.9.7
  app/app.go
  app/upgrades/v0_9_7/constants.go
  app/upgrades/v0_9_7/upgrades.go
Labels: ci

#400 PRT-167-Data-reliability-for-rest-tendermint-grpc-optional-params
  protocol/chainlib/chainproxy/rpcInterfaceMessages/grpcMessage.go
  protocol/chainlib/chainproxy/rpcInterfaceMessages/restMessage.go
  protocol/chainlib/chainproxy/rpcInterfaceMessages/restMessage_test.go
  protocol/chainlib/common.go
  protocol/chainlib/common_test.go
  protocol/chainlib/grpc.go
  protocol/chainlib/rest.go
  protocol/chainlib/rest_test.go
  protocol/parser/parser.go
  protocol/rpcprovider/rewardserver/reward_server.go
  protocol/rpcprovider/rpcprovider_server.go
Labels: enhancement

#430 CNS-374: fix vrfIndex mismatch between consumer and provider
  protocol/lavasession/end_to_end_lavasession_test.go
  protocol/lavasession/provider_session_manager.go
  protocol/lavasession/provider_session_manager_test.go
  protocol/lavasession/provider_types.go
  protocol/rpcprovider/rpcprovider.go
  protocol/rpcprovider/rpcprovider_server.go
  protocol/statetracker/provider_state_tracker.go
  protocol/statetracker/state_query.go
Labels: bug

#439 PRT-634 add avalanche spec
  cookbook/specs/spec_add_avalanche.json
  docs/static/openapi.yml
  go.mod
  proto/spec/service_api.proto
  protocol/chainlib/chainlib.go
  protocol/chainlib/jsonRPC.go
  protocol/chainlib/tendermintRPC.go
  protocol/rpcprovider/rpcprovider.go
  scripts/init_chain_commands.sh
  scripts/pre_setups/init_avalanch_only.sh
  scripts/setup_providers.sh
  x/spec/types/service_api.pb.go
Labels: enhancement

#438 PRT-629 fixing account sequence mismatch error in providers.
  protocol/statetracker/tx_sender.go
Labels: bug
